// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./../../src/layouts/admin/index.vue')['default']
    AdminHistoryMenu: typeof import('./../../src/layouts/admin/historyMenu.vue')['default']
    AdminMenu: typeof import('./../../src/layouts/admin/menu.vue')['default']
    AdminNavbar: typeof import('./../../src/layouts/admin/navbar.vue')['default']
    AdminXiaoxin: typeof import('./../../src/layouts/admin/xiaoxin/index.vue')['default']
    Auth: typeof import('./../../src/layouts/auth/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error: typeof import('./../../src/layouts/error/index.vue')['default']
    Front: typeof import('./../../src/layouts/front/index.vue')['default']
    IconUpSquare: typeof import('@icon-park/vue-next')['UpSquare']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatarMenu: typeof import('./../../src/components/userAvatarMenu.vue')['default']
    XiaoxinAnimateList: typeof import('./../../src/components/xiaoxin/animateList.vue')['default']
    XiaoxinBreadcrumb: typeof import('./../../src/components/xiaoxin/breadcrumb.vue')['default']
    XiaoxinCard: typeof import('./../../src/components/xiaoxin/card.vue')['default']
    XiaoxinError: typeof import('./../../src/components/xiaoxin/error.vue')['default']
    XiaoxinFormButton: typeof import('./../../src/components/xiaoxin/formButton.vue')['default']
    XiaoxinFormInput: typeof import('./../../src/components/xiaoxin/formInput.vue')['default']
    XiaoxinFullscreen: typeof import('./../../src/components/xiaoxin/fullscreen.vue')['default']
    XiaoxinMarkdownEditor: typeof import('./../../src/components/xiaoxin/markdownEditor.vue')['default']
    XiaoxinMarkdownPreview: typeof import('./../../src/components/xiaoxin/markdownPreview.vue')['default']
    XiaoxinPagination: typeof import('./../../src/components/xiaoxin/pagination.vue')['default']
    XiaoxinTab: typeof import('./../../src/components/xiaoxin/tab.vue')['default']
    XiaoxinUploadSingleImage: typeof import('./../../src/components/xiaoxin/uploadSingleImage.vue')['default']
    XiaoxinVideoPlayer: typeof import('./../../src/components/xiaoxin/videoPlayer.vue')['default']
    XiaoxinWangEditor: typeof import('./../../src/components/xiaoxin/wangEditor.vue')['default']
  }
}
